# Generated by Django 4.2.27 on 2026-01-18 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_scraperrun_scraperconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug for the page (e.g., 'home' for /p/home/)", max_length=255, unique=True)),
                ('title', models.CharField(help_text='Internal title for the page', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('html_json', models.JSONField(blank=True, default=dict, help_text='GrapesJS components JSON')),
                ('html', models.TextField(blank=True, help_text='Rendered HTML from GrapesJS')),
                ('css', models.TextField(blank=True, help_text='CSS from GrapesJS')),
                ('seo_title', models.CharField(blank=True, help_text='SEO page title', max_length=255)),
                ('seo_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('seo_image', models.URLField(blank=True, help_text='SEO image URL')),
                ('form_settings', models.JSONField(blank=True, default=dict, help_text='Form configuration (fields, validation, etc.)')),
                ('brevo_list_id', models.IntegerField(blank=True, help_text='Brevo list ID for form submissions', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Component name', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('hero', 'Hero Section'), ('form', 'Form'), ('stats', 'Statistics'), ('testimonial', 'Testimonial'), ('cta', 'Call to Action'), ('feature', 'Feature'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Component description')),
                ('html_snippet', models.TextField(help_text='HTML snippet for the component')),
                ('css_snippet', models.TextField(blank=True, help_text='CSS for the component')),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='GrapesJS component JSON')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Preview thumbnail URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Component',
                'verbose_name_plural': 'Page Components',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Submitted form data')),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pages.landingpage')),
                ('lead', models.ForeignKey(blank=True, help_text='Associated lead record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_submissions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Page Submission',
                'verbose_name_plural': 'Page Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Sequential version number')),
                ('html_json', models.JSONField(default=dict)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, help_text='Optional note about this version', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.landingpage')),
            ],
            options={
                'verbose_name': 'Page Version',
                'verbose_name_plural': 'Page Versions',
                'ordering': ['-version'],
                'unique_together': {('landing_page', 'version')},
            },
        ),
    ]
