# Generated by Django 4.2.27 on 2026-01-18 20:55

from django.db import migrations
import os


def load_landing_html():
    """Load the existing landing page HTML"""
    landing_path = os.path.join(os.path.dirname(__file__), '../../../..', 'landing', 'index.html')
    try:
        with open(landing_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return ""


def seed_landing_page(apps, schema_editor):
    """Import existing landing page and create component seeds"""
    LandingPage = apps.get_model('pages', 'LandingPage')
    PageComponent = apps.get_model('pages', 'PageComponent')
    
    # Load the existing landing page HTML
    landing_html = load_landing_html()
    
    if landing_html:
        # Create the main landing page (published)
        LandingPage.objects.create(
            slug='home',
            title='LUCA Lead Finder - Home',
            status='published',
            html=landing_html,
            css='',  # CSS is loaded from external file in original
            html_json={},  # Will be built in GrapesJS
            seo_title='LUCA Lead Finder - KI-gestützte Lead-Generierung für Vertriebsprofis',
            seo_description='Automatische Lead-Generierung mit KI. 95% mit Handynummer. 24/7 Automatisiert. Direktes Kleinanzeigen-Crawling & Telefonbuch-Enrichment.',
            brevo_list_id=None,
        )
    
    # Create Hero component
    PageComponent.objects.create(
        name='Hero Section',
        slug='hero-section',
        category='hero',
        description='Main hero section with gradient background and CTA',
        html_snippet='''
            <section class="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
                <div class="container mx-auto px-6 text-center">
                    <h1 class="text-6xl font-black text-white mb-6">
                        LUCA <span class="text-cyan-400">Lead Finder</span>
                    </h1>
                    <p class="text-2xl text-gray-300 mb-8">
                        KI-gestützte Lead-Generierung für Vertriebsprofis
                    </p>
                    <a href="#contact" class="px-8 py-4 bg-cyan-500 text-white font-bold rounded-lg hover:bg-cyan-600">
                        Jetzt starten
                    </a>
                </div>
            </section>
        ''',
        css_snippet='',
        is_active=True,
    )
    
    # Create Stats component
    PageComponent.objects.create(
        name='Stats Counter',
        slug='stats-counter',
        category='stats',
        description='Statistics counter with animated numbers',
        html_snippet='''
            <div class="py-16 bg-gradient-to-r from-cyan-500 to-blue-600">
                <div class="container mx-auto px-6">
                    <div class="grid grid-cols-1 md:grid-cols-4 gap-8 text-center text-white">
                        <div><div class="text-5xl font-bold mb-2">50000+</div><div class="text-xl">Leads generiert</div></div>
                        <div><div class="text-5xl font-bold mb-2">95%</div><div class="text-xl">mit Handynummer</div></div>
                        <div><div class="text-5xl font-bold mb-2">15+</div><div class="text-xl">Datenquellen</div></div>
                        <div><div class="text-5xl font-bold mb-2">24/7</div><div class="text-xl">Automatisiert</div></div>
                    </div>
                </div>
            </div>
        ''',
        css_snippet='',
        is_active=True,
    )
    
    # Create Form component
    PageComponent.objects.create(
        name='Lead Form',
        slug='lead-form',
        category='form',
        description='Contact form for lead generation',
        html_snippet='''
            <form data-landing-form class="max-w-md mx-auto p-6 bg-white rounded-lg shadow-lg">
                <h3 class="text-2xl font-bold mb-4 text-gray-800">Kostenlos testen</h3>
                <input type="text" name="name" placeholder="Ihr Name" required class="w-full mb-4 px-4 py-2 border rounded" />
                <input type="email" name="email" placeholder="Ihre E-Mail" required class="w-full mb-4 px-4 py-2 border rounded" />
                <input type="tel" name="phone" placeholder="Telefon (optional)" class="w-full mb-4 px-4 py-2 border rounded" />
                <button type="submit" class="w-full bg-cyan-500 text-white font-bold py-3 rounded hover:bg-cyan-600">
                    Absenden
                </button>
            </form>
        ''',
        css_snippet='',
        is_active=True,
    )
    
    # Create Testimonial component
    PageComponent.objects.create(
        name='Testimonials',
        slug='testimonials',
        category='testimonial',
        description='Customer testimonials section',
        html_snippet='''
            <div class="py-16 bg-gray-100">
                <div class="container mx-auto px-6">
                    <h2 class="text-4xl font-bold text-center mb-12">Was unsere Kunden sagen</h2>
                    <div class="grid md:grid-cols-3 gap-8">
                        <div class="bg-white p-6 rounded-lg shadow">
                            <p class="text-gray-700 italic mb-4">"Exzellenter Service! Die Leads sind hochwertig."</p>
                            <p class="font-bold">Max Mustermann, CEO</p>
                        </div>
                        <div class="bg-white p-6 rounded-lg shadow">
                            <p class="text-gray-700 italic mb-4">"Die KI-gestützte Lead-Generierung hat unsere Conversion-Rate verdoppelt."</p>
                            <p class="font-bold">Anna Schmidt, Vertriebsleiterin</p>
                        </div>
                        <div class="bg-white p-6 rounded-lg shadow">
                            <p class="text-gray-700 italic mb-4">"Einfach zu bedienen und extrem effektiv."</p>
                            <p class="font-bold">Jonas Weber, Sales Manager</p>
                        </div>
                    </div>
                </div>
            </div>
        ''',
        css_snippet='',
        is_active=True,
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded data"""
    LandingPage = apps.get_model('pages', 'LandingPage')
    PageComponent = apps.get_model('pages', 'PageComponent')
    
    LandingPage.objects.filter(slug='home').delete()
    PageComponent.objects.filter(slug__in=[
        'hero-section', 'stats-counter', 'lead-form', 'testimonials'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_landing_page, reverse_seed),
    ]
