# Generated by Django 4.2.27 on 2026-01-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='dns_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='dns_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='entry_point',
            field=models.CharField(default='index.html', help_text='Main entry file for uploaded site', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hosting_type',
            field=models.CharField(choices=[('internal', 'Internes Hosting'), ('strato', 'STRATO Domain'), ('custom', 'Benutzerdefinierte Domain')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='is_uploaded_site',
            field=models.BooleanField(default=False, help_text='True if this is an uploaded website (ZIP/files)'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ssl_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='strato_main_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='strato_subdomain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='uploaded_files_path',
            field=models.CharField(blank=True, help_text='Path to uploaded files directory', max_length=500),
        ),
        migrations.CreateModel(
            name='DomainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strato_customer_id', models.CharField(blank=True, max_length=100)),
                ('strato_api_key_encrypted', models.TextField(blank=True)),
                ('required_a_record', models.GenericIPAddressField(blank=True, null=True)),
                ('required_cname', models.CharField(blank=True, max_length=255)),
                ('required_txt_record', models.TextField(blank=True)),
                ('last_dns_check', models.DateTimeField(blank=True, null=True)),
                ('dns_check_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_config', to='pages.landingpage')),
            ],
            options={
                'verbose_name': 'Domain Configuration',
                'verbose_name_plural': 'Domain Configurations',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='landing_pages/uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('relative_path', models.CharField(help_text="Path relative to site root (e.g., 'css/style.css')", max_length=500)),
                ('file_type', models.CharField(blank=True, help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='pages.landingpage')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['relative_path'],
                'unique_together': {('landing_page', 'relative_path')},
            },
        ),
    ]
