# Generated by Django 4.2.27 on 2026-01-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_add_seo_enhancements'),
        ('pages', '0012_add_social_media_fields'),
    ]

    operations = [
    ]
