# Generated by Django 4.2.27 on 2026-01-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0013_merge_20260121_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='OpenGraph description (defaults to seo_description)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='og_image',
            field=models.URLField(blank=True, help_text='OpenGraph image URL (defaults to seo_image)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='OpenGraph title (defaults to seo_title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='og_type',
            field=models.CharField(default='website', help_text='OpenGraph type (website, article, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50),
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups related changes together (e.g., multi-file save)')),
                ('change_type', models.CharField(choices=[('page_content', 'Page Content Change'), ('file_edit', 'File Edit'), ('file_create', 'File Create'), ('file_delete', 'File Delete'), ('file_rename', 'File Rename'), ('settings', 'Settings Change'), ('asset_upload', 'Asset Upload'), ('asset_delete', 'Asset Delete')], max_length=20)),
                ('target_path', models.CharField(blank=True, help_text='File path or component identifier affected by this change', max_length=500)),
                ('version', models.PositiveIntegerField(help_text='Sequential version number within this page')),
                ('parent_version', models.PositiveIntegerField(blank=True, help_text='Previous version (for branching support)', null=True)),
                ('content_before', models.TextField(blank=True, help_text='Content before the change (for undo)')),
                ('content_after', models.TextField(blank=True, help_text='Content after the change')),
                ('content_delta', models.TextField(blank=True, help_text='Delta/diff for efficient storage (optional)')),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 hash of content_after for integrity verification', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (file type, component type, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, help_text='User-provided note about this change', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorizing changes (e.g., ['release', 'v1.0'])")),
                ('is_snapshot', models.BooleanField(db_index=True, default=False, help_text='Mark this version as a snapshot/release point')),
                ('snapshot_name', models.CharField(blank=True, help_text="Name for this snapshot (e.g., 'Release 1.0', 'Backup before redesign')", max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelogs', to=settings.AUTH_USER_MODEL)),
                ('landing_page', models.ForeignKey(help_text='Page this change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='pages.landingpage')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='VersionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Snapshot name (e.g., 'v1.0.0', 'Pre-redesign backup')", max_length=100)),
                ('snapshot_type', models.CharField(choices=[('manual', 'Manual Snapshot'), ('auto', 'Automatic Snapshot'), ('release', 'Release'), ('backup', 'Backup')], default='manual', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this snapshot')),
                ('semver_major', models.PositiveIntegerField(blank=True, null=True)),
                ('semver_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('semver_patch', models.PositiveIntegerField(blank=True, null=True)),
                ('semver_prerelease', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changelog_version', models.ForeignKey(help_text='ChangeLog entry this snapshot references', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pages.changelog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pages.landingpage')),
            ],
            options={
                'verbose_name': 'Version Snapshot',
                'verbose_name_plural': 'Version Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landing_page', '-created_at'], name='pages_versi_landing_37a927_idx')],
            },
        ),
        migrations.CreateModel(
            name='UndoRedoStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Browser session identifier', max_length=255)),
                ('current_version', models.PositiveIntegerField(help_text='Current position in the version history')),
                ('max_version', models.PositiveIntegerField(help_text='Highest version number (for redo boundary)')),
                ('undo_stack', models.JSONField(default=list, help_text='List of transaction IDs that can be undone')),
                ('redo_stack', models.JSONField(default=list, help_text='List of transaction IDs that can be redone')),
                ('last_action', models.CharField(choices=[('undo', 'Undo'), ('redo', 'Redo'), ('edit', 'Edit')], default='edit', max_length=20)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_stacks', to='pages.landingpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_stacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Undo/Redo Stack',
                'verbose_name_plural': 'Undo/Redo Stacks',
                'indexes': [models.Index(fields=['landing_page', 'user', 'session_key'], name='pages_undor_landing_310812_idx')],
                'unique_together': {('landing_page', 'user', 'session_key')},
            },
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['landing_page', '-version'], name='pages_chang_landing_036863_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['transaction_id'], name='pages_chang_transac_d0bad0_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['landing_page', 'is_snapshot'], name='pages_chang_landing_937b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['created_at'], name='pages_chang_created_37399c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='changelog',
            unique_together={('landing_page', 'version')},
        ),
    ]
