# Generated by Django 4.2.27 on 2026-01-18 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Provider Name')),
                ('base_url', models.URLField(blank=True, verbose_name='Base API URL')),
                ('cost_per_1k_tokens_prompt', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per 1K Prompt Tokens (EUR)')),
                ('cost_per_1k_tokens_completion', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per 1K Completion Tokens (EUR)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(choices=[('lead_extraction', 'Lead Extraction'), ('lead_scoring', 'Lead Scoring'), ('dork_generation', 'Dork Generation'), ('content_analysis', 'Content Analysis'), ('data_enrichment', 'Data Enrichment'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('content', models.TextField(help_text='Use {placeholder} syntax for variables', verbose_name='Template Content')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('prompt_slug', models.CharField(blank=True, max_length=100, verbose_name='Prompt Template Slug')),
                ('tokens_prompt', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prompt Tokens')),
                ('tokens_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Completion Tokens')),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost (EUR)')),
                ('latency_ms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Latency (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Request ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ai_config_a_created_e6e7c1_idx'), models.Index(fields=['provider', 'model'], name='ai_config_a_provide_2c271c_idx'), models.Index(fields=['success'], name='ai_config_a_success_10b51f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name (slug)')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('default_temperature', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Default Temperature')),
                ('default_top_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Default Top P')),
                ('default_max_tokens', models.IntegerField(default=4000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Default Max Tokens')),
                ('cost_per_1k_tokens_prompt', models.DecimalField(blank=True, decimal_places=6, help_text='Leave blank to use provider default', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Override per 1K Prompt Tokens (EUR)')),
                ('cost_per_1k_tokens_completion', models.DecimalField(blank=True, decimal_places=6, help_text='Leave blank to use provider default', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Override per 1K Completion Tokens (EUR)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_config.aiprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature')),
                ('top_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Top P')),
                ('max_tokens', models.IntegerField(default=4000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Tokens')),
                ('learning_rate', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Learning Rate')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily Budget (EUR)')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Budget (EUR)')),
                ('confidence_threshold', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Confidence Threshold')),
                ('retry_limit', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retry Limit')),
                ('timeout_seconds', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Timeout (seconds)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_configs', to='ai_config.aimodel', verbose_name='Default Model')),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_configs', to='ai_config.aiprovider', verbose_name='Default Provider')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
