# Generated by Django 4.2.27 on 2026-01-18 20:30

from django.db import migrations
from decimal import Decimal


def load_default_data(apps, schema_editor):
    """Load default AI providers, models, config, and prompt templates"""
    AIProvider = apps.get_model('ai_config', 'AIProvider')
    AIModel = apps.get_model('ai_config', 'AIModel')
    AIConfig = apps.get_model('ai_config', 'AIConfig')
    PromptTemplate = apps.get_model('ai_config', 'PromptTemplate')
    
    # Create OpenAI Provider
    openai = AIProvider.objects.create(
        name='OpenAI',
        base_url='https://api.openai.com/v1',
        cost_per_1k_tokens_prompt=Decimal('0.00015'),  # $0.15 per 1M tokens = €0.00015 per 1K
        cost_per_1k_tokens_completion=Decimal('0.0006'),  # $0.60 per 1M tokens = €0.0006 per 1K
        active=True
    )
    
    # Create OpenAI Models
    gpt4o_mini = AIModel.objects.create(
        provider=openai,
        name='gpt-4o-mini',
        display_name='GPT-4o Mini',
        default_temperature=0.3,
        default_top_p=1.0,
        default_max_tokens=4000,
        cost_per_1k_tokens_prompt=Decimal('0.00015'),
        cost_per_1k_tokens_completion=Decimal('0.0006'),
        active=True
    )
    
    AIModel.objects.create(
        provider=openai,
        name='gpt-4o',
        display_name='GPT-4o',
        default_temperature=0.3,
        default_top_p=1.0,
        default_max_tokens=4000,
        cost_per_1k_tokens_prompt=Decimal('0.005'),  # $5 per 1M tokens
        cost_per_1k_tokens_completion=Decimal('0.015'),  # $15 per 1M tokens
        active=True
    )
    
    # Create Perplexity Provider
    perplexity = AIProvider.objects.create(
        name='Perplexity',
        base_url='https://api.perplexity.ai',
        cost_per_1k_tokens_prompt=Decimal('0.0002'),  # Indicative cost
        cost_per_1k_tokens_completion=Decimal('0.0002'),
        active=True
    )
    
    # Create Perplexity Model
    AIModel.objects.create(
        provider=perplexity,
        name='sonar-small',
        display_name='Sonar Small',
        default_temperature=0.3,
        default_top_p=1.0,
        default_max_tokens=4000,
        cost_per_1k_tokens_prompt=Decimal('0.0002'),
        cost_per_1k_tokens_completion=Decimal('0.0002'),
        active=True
    )
    
    # Create default AIConfig
    AIConfig.objects.create(
        temperature=0.3,
        top_p=1.0,
        max_tokens=4000,
        learning_rate=0.01,
        daily_budget=Decimal('5.0'),
        monthly_budget=Decimal('150.0'),
        confidence_threshold=0.35,
        retry_limit=2,
        timeout_seconds=30,
        default_provider=openai,
        default_model=gpt4o_mini,
        is_active=True
    )
    
    # Create Prompt Templates
    PromptTemplate.objects.create(
        slug='lead_extraction',
        title='Lead Extraction',
        category='lead_extraction',
        content="""Extract lead information from the following content.

Content: {content}

Please extract:
- Name: Full name of the person
- Role: Job title or position
- Company: Company name
- Email: Email address if available
- Phone: Phone number if available
- Location: City or region

Return the information in a structured format.""",
        description='Template for extracting lead information from web content',
        is_active=True
    )
    
    PromptTemplate.objects.create(
        slug='lead_scoring',
        title='Lead Scoring',
        category='lead_scoring',
        content="""Score the following lead based on quality and relevance for sales recruitment.

Lead Information:
Name: {name}
Role: {role}
Company: {company}
Location: {location}
Content: {content}

Scoring Criteria:
- Sales/Vertrieb role relevance (0-40 points)
- Contact information completeness (0-20 points)
- Location match (NRW region) (0-20 points)
- Experience indicators (0-20 points)

Provide:
1. Total score (0-100)
2. Brief reasoning
3. Confidence level (0-1)""",
        description='Template for scoring lead quality and relevance',
        is_active=True
    )
    
    PromptTemplate.objects.create(
        slug='dork_generation',
        title='Google Dork Generation',
        category='dork_generation',
        content="""Generate effective Google search dorks for finding sales professionals in {region}.

Requirements:
- Target: {target_role}
- Region: {region}
- Focus: Contact information (email, phone)

Generate 5 diverse search dorks that:
1. Find professionals with the target role
2. Include contact information
3. Are specific to the region
4. Use advanced operators (site:, inurl:, intitle:, OR, AND)
5. Avoid job boards and generic sites

Return as a JSON array of strings.""",
        description='Template for generating optimized search dorks',
        is_active=True
    )
    
    PromptTemplate.objects.create(
        slug='content_analysis',
        title='Content Analysis',
        category='content_analysis',
        content="""Analyze the following content for sales recruitment relevance.

Content: {content}
URL: {url}

Analyze:
1. Is this a personal profile or company recruitment page?
2. Does it contain contact information?
3. Is the person in a sales/vertrieb role?
4. What's the quality level (high/medium/low)?
5. Key signals (positive and negative)

Provide structured analysis with confidence score.""",
        description='Template for analyzing content relevance and quality',
        is_active=True
    )
    
    PromptTemplate.objects.create(
        slug='data_enrichment',
        title='Data Enrichment',
        category='data_enrichment',
        content="""Enrich the following lead information with additional context.

Current Information:
Name: {name}
Role: {role}
Company: {company}
Location: {location}

Available Context: {context}

Provide:
1. Inferred missing information (email format, phone area code)
2. Company size estimation
3. Industry classification
4. Hiring volume indicators
5. Best contact approach

Use conservative estimates and mark confidence levels.""",
        description='Template for enriching lead data with contextual information',
        is_active=True
    )


def remove_default_data(apps, schema_editor):
    """Remove default data on migration rollback"""
    AIProvider = apps.get_model('ai_config', 'AIProvider')
    AIModel = apps.get_model('ai_config', 'AIModel')
    AIConfig = apps.get_model('ai_config', 'AIConfig')
    PromptTemplate = apps.get_model('ai_config', 'PromptTemplate')
    
    # Delete in reverse order to respect foreign keys
    PromptTemplate.objects.all().delete()
    AIConfig.objects.all().delete()
    AIModel.objects.all().delete()
    AIProvider.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_data, remove_default_data),
    ]
