# Generated by Django 4.2.27 on 2026-01-20

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0002_load_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DorkPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(db_index=True, verbose_name='Search Query')),
                ('query_hash', models.CharField(help_text='SHA-256 hash of the query for fast lookups', max_length=64, unique=True, verbose_name='Query Hash')),
                ('times_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Times Used')),
                ('leads_found', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leads Found')),
                ('phone_leads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leads with Phone')),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Success Rate')),
                ('pool', models.CharField(choices=[('core', 'Core'), ('explore', 'Explore')], default='explore', max_length=20, verbose_name='Pool')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dork Performance',
                'verbose_name_plural': 'Dork Performance Metrics',
                'ordering': ['-success_rate', '-phone_leads'],
            },
        ),
        migrations.CreateModel(
            name='SourcePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domain')),
                ('leads_found', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Leads Found')),
                ('leads_with_phone', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leads with Phone')),
                ('avg_quality', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Average Quality Score')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked/Disabled')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Blocked Reason')),
                ('total_visits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Visits')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Last Visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source Performance',
                'verbose_name_plural': 'Source Performance Metrics',
                'ordering': ['-avg_quality', '-leads_with_phone'],
            },
        ),
        migrations.CreateModel(
            name='PatternSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('phone', 'Phone Pattern'), ('domain', 'Domain Pattern'), ('query_term', 'Query Term'), ('url_path', 'URL Path'), ('content_signal', 'Content Signal'), ('extraction', 'Extraction Pattern')], db_index=True, max_length=50, verbose_name='Pattern Type')),
                ('pattern_value', models.TextField(verbose_name='Pattern Value')),
                ('pattern_hash', models.CharField(help_text='Hash of type + value for uniqueness', max_length=64, verbose_name='Pattern Hash')),
                ('occurrences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Occurrences')),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Confidence Score')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('last_success', models.DateTimeField(blank=True, null=True, verbose_name='Last Success')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pattern Success',
                'verbose_name_plural': 'Pattern Success Metrics',
                'ordering': ['-confidence', '-occurrences'],
                'unique_together': {('pattern_type', 'pattern_hash')},
            },
        ),
        migrations.CreateModel(
            name='TelefonbuchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(help_text='Hash of the lookup query', max_length=64, unique=True, verbose_name='Query Hash')),
                ('query_text', models.TextField(help_text='Original query for debugging', verbose_name='Query Text')),
                ('results_json', models.JSONField(help_text='Cached lookup results', verbose_name='Results (JSON)')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Cache expiration timestamp', verbose_name='Expires At')),
                ('hits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cache Hits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telefonbuch Cache',
                'verbose_name_plural': 'Telefonbuch Cache Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dorkperformance',
            index=models.Index(fields=['-success_rate', '-phone_leads'], name='ai_config_d_success_e89a06_idx'),
        ),
        migrations.AddIndex(
            model_name='dorkperformance',
            index=models.Index(fields=['pool', '-success_rate'], name='ai_config_d_pool_cd6c55_idx'),
        ),
        migrations.AddIndex(
            model_name='dorkperformance',
            index=models.Index(fields=['-last_used'], name='ai_config_d_last_us_d0aaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceperformance',
            index=models.Index(fields=['-avg_quality', '-leads_with_phone'], name='ai_config_s_avg_qua_c64b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceperformance',
            index=models.Index(fields=['is_blocked'], name='ai_config_s_is_bloc_8bc6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceperformance',
            index=models.Index(fields=['-last_visit'], name='ai_config_s_last_vi_57e4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='patternsuccess',
            index=models.Index(fields=['pattern_type', '-confidence'], name='ai_config_p_pattern_d5e1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='patternsuccess',
            index=models.Index(fields=['-occurrences'], name='ai_config_p_occurr_e1a5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='patternsuccess',
            index=models.Index(fields=['-last_success'], name='ai_config_p_last_su_c7a4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='telefonbuchcache',
            index=models.Index(fields=['expires_at'], name='ai_config_t_expires_62f2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='telefonbuchcache',
            index=models.Index(fields=['-created_at'], name='ai_config_t_created_12e0f3_idx'),
        ),
    ]
