# Generated by Django 4.2.27 on 2026-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0003_add_learning_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dorkperformance',
            new_name='ai_config_d_success_4febc4_idx',
            old_name='ai_config_d_success_e89a06_idx',
        ),
        migrations.RenameIndex(
            model_name='dorkperformance',
            new_name='ai_config_d_pool_67098c_idx',
            old_name='ai_config_d_pool_cd6c55_idx',
        ),
        migrations.RenameIndex(
            model_name='dorkperformance',
            new_name='ai_config_d_last_us_de8283_idx',
            old_name='ai_config_d_last_us_d0aaf0_idx',
        ),
        migrations.RenameIndex(
            model_name='patternsuccess',
            new_name='ai_config_p_pattern_3784d4_idx',
            old_name='ai_config_p_pattern_d5e1b9_idx',
        ),
        migrations.RenameIndex(
            model_name='patternsuccess',
            new_name='ai_config_p_occurre_1c8cae_idx',
            old_name='ai_config_p_occurr_e1a5e8_idx',
        ),
        migrations.RenameIndex(
            model_name='patternsuccess',
            new_name='ai_config_p_last_su_77da66_idx',
            old_name='ai_config_p_last_su_c7a4a7_idx',
        ),
        migrations.RenameIndex(
            model_name='sourceperformance',
            new_name='ai_config_s_avg_qua_49cecc_idx',
            old_name='ai_config_s_avg_qua_c64b6a_idx',
        ),
        migrations.RenameIndex(
            model_name='sourceperformance',
            new_name='ai_config_s_is_bloc_ad9a1b_idx',
            old_name='ai_config_s_is_bloc_8bc6c9_idx',
        ),
        migrations.RenameIndex(
            model_name='sourceperformance',
            new_name='ai_config_s_last_vi_4717c9_idx',
            old_name='ai_config_s_last_vi_57e4e4_idx',
        ),
        migrations.RenameIndex(
            model_name='telefonbuchcache',
            new_name='ai_config_t_expires_9c69c9_idx',
            old_name='ai_config_t_expires_62f2e5_idx',
        ),
        migrations.RenameIndex(
            model_name='telefonbuchcache',
            new_name='ai_config_t_created_7fd8c4_idx',
            old_name='ai_config_t_created_12e0f3_idx',
        ),
    ]
