# Generated by Django 4.2.27 on 2026-01-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_add_analytics_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='app_setting_timesta_fdc377_idx',
            old_name='app_setting_timesta_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='app_setting_action_4e9f21_idx',
            old_name='app_setting_action_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='app_setting_timesta_547e9f_idx',
            old_name='app_setting_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='app_setting_session_27306d_idx',
            old_name='app_setting_session_idx',
        ),
    ]
