# Generated by Django 4.2.27 on 2026-01-19 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('report_type', models.CharField(choices=[('lead_overview', 'Lead-Übersicht'), ('scraper_performance', 'Scraper-Performance'), ('conversion_funnel', 'Conversion-Funnel'), ('source_analysis', 'Quellen-Analyse'), ('cost_analysis', 'Kosten-Analyse')], max_length=50, verbose_name='Report-Typ')),
                ('frequency', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], max_length=20, verbose_name='Häufigkeit')),
                ('recipients', models.JSONField(default=list, help_text='Liste von Email-Adressen', verbose_name='Empfänger')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Lauf')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Nächster Lauf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Report-Zeitplan',
                'verbose_name_plural': 'Report-Zeitpläne',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='Report-Typ')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generiert am')),
                ('period_start', models.DateField(verbose_name='Zeitraum Start')),
                ('period_end', models.DateField(verbose_name='Zeitraum Ende')),
                ('data', models.JSONField(default=dict, verbose_name='Report-Daten')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Dateipfad')),
                ('file_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Dateiformat')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generiert von')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='reports.reportschedule', verbose_name='Zeitplan')),
            ],
            options={
                'verbose_name': 'Report-Historie',
                'verbose_name_plural': 'Report-Historien',
                'ordering': ['-generated_at'],
            },
        ),
    ]
