# Generated by Django 4.2.27 on 2026-01-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_create_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(choices=[('welcome', 'Willkommen'), ('follow_up', 'Follow-Up'), ('reminder', 'Erinnerung'), ('confirmation', 'Bestätigung'), ('newsletter', 'Newsletter'), ('custom', 'Benutzerdefiniert')], max_length=50, verbose_name='Kategorie')),
                ('subject', models.CharField(help_text='Betreff mit {variablen}', max_length=255, verbose_name='Betreff')),
                ('html_content', models.TextField(help_text='HTML-Inhalt mit {variablen}', verbose_name='HTML-Inhalt')),
                ('text_content', models.TextField(blank=True, help_text='Plain-Text Fallback', verbose_name='Text-Inhalt')),
                ('available_variables', models.JSONField(default=list, help_text="Liste der verfügbaren Variablen: ['name', 'email', 'company']", verbose_name='Verfügbare Variablen')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='KI-generiert')),
                ('ai_prompt_used', models.TextField(blank=True, verbose_name='Verwendeter KI-Prompt')),
                ('brevo_template_id', models.IntegerField(blank=True, help_text='Falls mit Brevo synchronisiert', null=True, verbose_name='Brevo Template-ID')),
                ('sync_to_brevo', models.BooleanField(default=False, verbose_name='Mit Brevo synchronisieren')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('send_count', models.IntegerField(default=0, verbose_name='Anzahl Versendungen')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesendet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Email-Template',
                'verbose_name_plural': 'Email-Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('html_content', models.TextField(verbose_name='HTML-Inhalt')),
                ('text_content', models.TextField(blank=True, verbose_name='Text-Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Notiz')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email_templates.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template-Version',
                'verbose_name_plural': 'Template-Versionen',
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='An (Email)')),
                ('subject_rendered', models.CharField(max_length=255, verbose_name='Betreff (gerendert)')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('opened', 'Geöffnet'), ('clicked', 'Geklickt'), ('bounced', 'Bounced'), ('failed', 'Fehlgeschlagen')], default='sent', max_length=20, verbose_name='Status')),
                ('brevo_message_id', models.CharField(blank=True, max_length=255, verbose_name='Brevo Nachricht-ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Geöffnet am')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Geklickt am')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_logs', to='leads.lead', verbose_name='Lead')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='email_templates.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Email-Versand-Log',
                'verbose_name_plural': 'Email-Versand-Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='email_templ_sent_at_91db0d_idx'), models.Index(fields=['status'], name='email_templ_status_f1b9ca_idx')],
            },
        ),
    ]
