# Generated by Django 4.2.27 on 2026-01-18 23:47

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """Erstellt Standard-Email-Templates"""
    EmailTemplate = apps.get_model('email_templates', 'EmailTemplate')
    
    templates = [
        {
            'slug': 'welcome_new_lead',
            'name': 'Willkommen - Neuer Lead',
            'category': 'welcome',
            'subject': 'Willkommen bei LUCA, {name}!',
            'html_content': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #06b6d4;">Hallo {name}!</h1>
        
        <p>Vielen Dank für Ihr Interesse an unseren Recruiting-Services.</p>
        
        <p>Wir freuen uns, Sie als neuen Lead in unserem System begrüßen zu dürfen. 
        Unser Team wird sich in Kürze bei Ihnen melden.</p>
        
        <div style="background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Ihre Daten:</strong></p>
            <p style="margin: 5px 0;">📧 Email: {email}</p>
            <p style="margin: 5px 0;">🏢 Firma: {company}</p>
        </div>
        
        <p>Bei Fragen stehen wir Ihnen gerne zur Verfügung.</p>
        
        <p>Mit freundlichen Grüßen<br>
        Ihr LUCA Team</p>
    </div>
</body>
</html>
''',
            'text_content': '''Hallo {name}!

Vielen Dank für Ihr Interesse an unseren Recruiting-Services.

Wir freuen uns, Sie als neuen Lead in unserem System begrüßen zu dürfen. 
Unser Team wird sich in Kürze bei Ihnen melden.

Ihre Daten:
- Email: {email}
- Firma: {company}

Bei Fragen stehen wir Ihnen gerne zur Verfügung.

Mit freundlichen Grüßen
Ihr LUCA Team''',
            'available_variables': ['name', 'email', 'company'],
            'is_active': True,
        },
        {
            'slug': 'follow_up_no_response',
            'name': 'Follow-Up - Keine Antwort',
            'category': 'follow_up',
            'subject': 'Noch Interesse, {name}?',
            'html_content': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #06b6d4;">Hallo {name},</h1>
        
        <p>vor einigen Tagen haben wir Ihnen eine Nachricht geschickt, 
        aber noch keine Antwort erhalten.</p>
        
        <p>Haben Sie noch Interesse an unseren Recruiting-Services? 
        Wir würden uns freuen, von Ihnen zu hören!</p>
        
        <div style="background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <p style="margin: 0;">📞 Kontaktieren Sie uns:</p>
            <p style="margin: 5px 0;">Email: {email}</p>
        </div>
        
        <p>Wir freuen uns auf Ihre Rückmeldung.</p>
        
        <p>Mit freundlichen Grüßen<br>
        Ihr LUCA Team</p>
    </div>
</body>
</html>
''',
            'text_content': '''Hallo {name},

vor einigen Tagen haben wir Ihnen eine Nachricht geschickt, 
aber noch keine Antwort erhalten.

Haben Sie noch Interesse an unseren Recruiting-Services? 
Wir würden uns freuen, von Ihnen zu hören!

📞 Kontaktieren Sie uns:
Email: {email}

Wir freuen uns auf Ihre Rückmeldung.

Mit freundlichen Grüßen
Ihr LUCA Team''',
            'available_variables': ['name', 'email'],
            'is_active': True,
        },
        {
            'slug': 'meeting_confirmation',
            'name': 'Meeting-Bestätigung',
            'category': 'confirmation',
            'subject': 'Termin bestätigt: {date} um {time}',
            'html_content': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #06b6d4;">Meeting-Bestätigung</h1>
        
        <p>Hallo {name},</p>
        
        <p>hiermit bestätigen wir unser Meeting:</p>
        
        <div style="background-color: #f0f9ff; padding: 20px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #06b6d4;">
            <p style="margin: 5px 0; font-size: 18px;"><strong>📅 {date}</strong></p>
            <p style="margin: 5px 0; font-size: 18px;"><strong>🕐 {time}</strong></p>
            <p style="margin: 5px 0;">📧 {email}</p>
        </div>
        
        <p>Wir freuen uns auf das Gespräch!</p>
        
        <p>Bei Fragen oder wenn Sie den Termin verschieben möchten, 
        melden Sie sich gerne bei uns.</p>
        
        <p>Mit freundlichen Grüßen<br>
        Ihr LUCA Team</p>
    </div>
</body>
</html>
''',
            'text_content': '''Meeting-Bestätigung

Hallo {name},

hiermit bestätigen wir unser Meeting:

📅 {date}
🕐 {time}
📧 {email}

Wir freuen uns auf das Gespräch!

Bei Fragen oder wenn Sie den Termin verschieben möchten, 
melden Sie sich gerne bei uns.

Mit freundlichen Grüßen
Ihr LUCA Team''',
            'available_variables': ['name', 'email', 'date', 'time'],
            'is_active': True,
        },
        {
            'slug': 'newsletter_monthly',
            'name': 'Monatlicher Newsletter',
            'category': 'newsletter',
            'subject': 'LUCA Newsletter - Neuigkeiten im {date}',
            'html_content': '''
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #06b6d4;">LUCA Newsletter</h1>
        
        <p>Hallo {name},</p>
        
        <p>hier sind die Neuigkeiten dieses Monats:</p>
        
        <div style="background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="color: #06b6d4; margin-top: 0;">📰 Highlights</h3>
            <ul>
                <li>Neue Features im LUCA System</li>
                <li>Erfolgsgeschichten unserer Kunden</li>
                <li>Recruiting-Tipps für {company}</li>
            </ul>
        </div>
        
        <p>Verpassen Sie keine Updates - folgen Sie uns!</p>
        
        <p>Mit freundlichen Grüßen<br>
        Ihr LUCA Team</p>
        
        <p style="font-size: 12px; color: #666; margin-top: 30px;">
            Sie erhalten diese Email, weil Sie sich für unseren Newsletter angemeldet haben.
        </p>
    </div>
</body>
</html>
''',
            'text_content': '''LUCA Newsletter

Hallo {name},

hier sind die Neuigkeiten dieses Monats:

📰 Highlights
- Neue Features im LUCA System
- Erfolgsgeschichten unserer Kunden
- Recruiting-Tipps für {company}

Verpassen Sie keine Updates - folgen Sie uns!

Mit freundlichen Grüßen
Ihr LUCA Team

---
Sie erhalten diese Email, weil Sie sich für unseren Newsletter angemeldet haben.''',
            'available_variables': ['name', 'company', 'date'],
            'is_active': True,
        },
    ]
    
    for template_data in templates:
        EmailTemplate.objects.get_or_create(
            slug=template_data['slug'],
            defaults=template_data
        )


def remove_default_templates(apps, schema_editor):
    """Entfernt die Standard-Templates (für Rückgängig-Machen)"""
    EmailTemplate = apps.get_model('email_templates', 'EmailTemplate')
    slugs = [
        'welcome_new_lead',
        'follow_up_no_response',
        'meeting_confirmation',
        'newsletter_monthly',
    ]
    EmailTemplate.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
