# Generated by Django 4.2.27 on 2026-01-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_scraperrun_started_by_delete_scraperconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_templates', '0002_add_default_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('trigger_type', models.CharField(choices=[('lead_created', 'Lead erstellt'), ('lead_status_changed', 'Status geändert'), ('lead_score_reached', 'Score erreicht'), ('tag_added', 'Tag hinzugefügt'), ('time_based', 'Zeitbasiert (Cron)'), ('form_submitted', 'Formular eingereicht'), ('email_opened', 'Email geöffnet'), ('email_clicked', 'Email geklickt'), ('manual', 'Manuell ausgelöst')], max_length=50, verbose_name='Trigger-Typ')),
                ('trigger_config', models.JSONField(default=dict, verbose_name='Trigger-Konfiguration')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='Ausführungen')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt ausgeführt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Email-Flow',
                'verbose_name_plural': 'Email-Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('waiting', 'Wartet'), ('completed', 'Abgeschlossen'), ('paused', 'Pausiert'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('next_execution_at', models.DateTimeField(blank=True, null=True, verbose_name='Nächste Ausführung')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('execution_log', models.JSONField(default=list, verbose_name='Ausführungs-Log')),
            ],
            options={
                'verbose_name': 'Flow-Ausführung',
                'verbose_name_plural': 'Flow-Ausführungen',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Reihenfolge')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('action_type', models.CharField(choices=[('send_email', 'Email senden'), ('wait', 'Warten'), ('condition', 'Bedingung prüfen'), ('update_lead', 'Lead aktualisieren'), ('add_tag', 'Tag hinzufügen'), ('remove_tag', 'Tag entfernen'), ('webhook', 'Webhook aufrufen'), ('notify_team', 'Team benachrichtigen'), ('update_score', 'Score anpassen')], max_length=50, verbose_name='Aktion')),
                ('action_config', models.JSONField(default=dict, verbose_name='Aktions-Konfiguration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_templates.emailtemplate', verbose_name='Email-Template')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='email_templates.emailflow', verbose_name='Flow')),
            ],
            options={
                'verbose_name': 'Flow-Schritt',
                'verbose_name_plural': 'Flow-Schritte',
                'ordering': ['flow', 'order'],
                'unique_together': {('flow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FlowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Übersprungen')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('result_data', models.JSONField(default=dict, verbose_name='Ergebnis-Daten')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='email_templates.flowexecution', verbose_name='Ausführung')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_templates.flowstep', verbose_name='Schritt')),
            ],
            options={
                'verbose_name': 'Step-Ausführung',
                'verbose_name_plural': 'Step-Ausführungen',
                'ordering': ['execution', 'step__order'],
            },
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_templates.flowstep', verbose_name='Aktueller Schritt'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='email_templates.emailflow', verbose_name='Flow'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='leads.lead', verbose_name='Lead'),
        ),
    ]
