"""
Django settings for telis project.

Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application version
VERSION_FILE = Path(__file__).resolve().parent.parent.parent / 'VERSION'
try:
    with open(VERSION_FILE, 'r') as f:
        APP_VERSION = f.read().strip()
except FileNotFoundError:
    APP_VERSION = 'unknown'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-please-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    # Unfold must come before django.contrib.admin
    'unfold',
    'unfold.contrib.filters',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'leads.apps.LeadsConfig',
    'scraper_control',
    'ai_config',
    'pages.apps.PagesConfig',
    'email_templates.apps.EmailTemplatesConfig',
    'reports',
    'mailbox.apps.MailboxConfig',
    'app_settings.apps.AppSettingsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'telis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mailbox.context_processors.unread_email_count',
                'telis.context_processors.version_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'telis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Simple SQLite configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only add STATICFILES_DIRS if the static directory exists
if (BASE_DIR / 'static').exists():
    STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User-uploaded content)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Whitenoise configuration for serving static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True


# Scraper Configuration
SCRAPER_PATH = os.getenv('SCRAPER_PATH', '../')

# ==========================
# Brevo (Sendinblue) Settings
# ==========================
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')

# Helper function to get optional integer from env
def _get_optional_int(env_var: str) -> int:
    """Get optional integer from environment variable, returns None if not set or empty"""
    value = os.getenv(env_var)
    if value:
        try:
            return int(value)
        except (ValueError, TypeError):
            return None
    return None

BREVO_DEFAULT_LIST_ID = _get_optional_int('BREVO_DEFAULT_LIST_ID')
BREVO_LANDING_PAGE_LIST_ID = _get_optional_int('BREVO_LANDING_PAGE_LIST_ID')
BREVO_WELCOME_TEMPLATE_ID = _get_optional_int('BREVO_WELCOME_TEMPLATE_ID')

# Brevo Webhook Security
BREVO_WEBHOOK_SECRET = os.getenv('BREVO_WEBHOOK_SECRET', None)


# ==========================
# Authentication Settings
# ==========================
LOGIN_URL = 'crm-login'
LOGIN_REDIRECT_URL = 'crm-dashboard'
LOGOUT_REDIRECT_URL = 'crm-login'


# ==========================
# Django Unfold Configuration
# ==========================
UNFOLD = {
    "SITE_TITLE": "LUCA Command Center",
    "SITE_HEADER": "LUCA Command Center",
    "SITE_URL": "/",
    
    # Theme colors - cyan primary with gradient
    "COLORS": {
        "primary": {
            "50": "236 254 255",
            "100": "207 250 254",
            "200": "165 243 252",
            "300": "103 232 249",
            "400": "34 211 238",
            "500": "6 182 212",  # #06b6d4 - primary cyan
            "600": "8 145 178",  # #0891b2 - hover
            "700": "14 116 144",
            "800": "21 94 117",
            "900": "22 78 99",
            "950": "8 51 68",
        },
    },
    
    "THEME": "dark",  # Enable dark mode
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    
    # Sidebar navigation with icons and groups
    "SIDEBAR": {
        "show_search": True,  # Enable menu search
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Home",
                        "icon": "home",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Leads",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Alle Leads",
                        "icon": "people",
                        "link": "/admin/leads/lead/",
                    },
                    {
                        "title": "Anruflogs",
                        "icon": "phone",
                        "link": "/admin/leads/calllog/",
                    },
                    {
                        "title": "E-Mail Logs",
                        "icon": "email",
                        "link": "/admin/leads/emaillog/",
                    },
                    {
                        "title": "Sync Status",
                        "icon": "sync",
                        "link": "/admin/leads/syncstatus/",
                    },
                ],
            },
            {
                "title": "Scraper",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Konfiguration",
                        "icon": "settings",
                        "link": "/admin/scraper_control/scraperconfig/",
                    },
                    {
                        "title": "Scraper Runs",
                        "icon": "play_arrow",
                        "link": "/admin/scraper_control/scraperrun/",
                    },
                    {
                        "title": "Logs",
                        "icon": "description",
                        "link": "/admin/scraper_control/scraperlog/",
                    },
                ],
            },
            {
                "title": "AI-Einstellungen",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "AI-Konfiguration",
                        "icon": "smart_toy",
                        "link": "/admin/ai_config/aiconfig/",
                    },
                    {
                        "title": "AI-Provider",
                        "icon": "cloud",
                        "link": "/admin/ai_config/aiprovider/",
                    },
                    {
                        "title": "AI-Modelle",
                        "icon": "memory",
                        "link": "/admin/ai_config/aimodel/",
                    },
                    {
                        "title": "Prompt Templates",
                        "icon": "article",
                        "link": "/admin/ai_config/prompttemplate/",
                    },
                    {
                        "title": "Usage Logs",
                        "icon": "analytics",
                        "link": "/admin/ai_config/aiusagelog/",
                    },
                ],
            },
            {
                "title": "Landing Pages",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Seiten",
                        "icon": "web",
                        "link": "/admin/pages/landingpage/",
                    },
                    {
                        "title": "Komponenten",
                        "icon": "widgets",
                        "link": "/admin/pages/pagecomponent/",
                    },
                    {
                        "title": "Einreichungen",
                        "icon": "assignment",
                        "link": "/admin/pages/pagesubmission/",
                    },
                    {
                        "title": "Versionen",
                        "icon": "history",
                        "link": "/admin/pages/pageversion/",
                    },
                ],
            },
            {
                "title": "Email Templates",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Templates",
                        "icon": "email",
                        "link": "/admin/email_templates/emailtemplate/",
                    },
                    {
                        "title": "Versionen",
                        "icon": "history",
                        "link": "/admin/email_templates/emailtemplateversion/",
                    },
                    {
                        "title": "Versand-Logs",
                        "icon": "send",
                        "link": "/admin/email_templates/emailsendlog/",
                    },
                ],
            },
            {
                "title": "Mailbox",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Posteingang",
                        "icon": "inbox",
                        "link": "/crm/mailbox/",
                    },
                    {
                        "title": "Email-Konten",
                        "icon": "account_circle",
                        "link": "/admin/mailbox/emailaccount/",
                    },
                    {
                        "title": "Konversationen",
                        "icon": "forum",
                        "link": "/admin/mailbox/emailconversation/",
                    },
                    {
                        "title": "Emails",
                        "icon": "mail",
                        "link": "/admin/mailbox/email/",
                    },
                    {
                        "title": "Schnellantworten",
                        "icon": "speed",
                        "link": "/admin/mailbox/quickreply/",
                    },
                    {
                        "title": "Signaturen",
                        "icon": "draw",
                        "link": "/admin/mailbox/emailsignature/",
                    },
                    {
                        "title": "Labels",
                        "icon": "label",
                        "link": "/admin/mailbox/emaillabel/",
                    },
                ],
            },
            {
                "title": "Reports",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Report-Zeitpläne",
                        "icon": "schedule",
                        "link": "/admin/reports/reportschedule/",
                    },
                    {
                        "title": "Report-Historie",
                        "icon": "assessment",
                        "link": "/admin/reports/reporthistory/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Benutzer",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Gruppen",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
}
