# Generated by Django 6.0.1 on 2026-01-20 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Internal form name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for the form (e.g., 'contact-form')", max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Form description")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(default="Submit", help_text="Text for submit button", max_length=100),
                ),
                (
                    "success_message",
                    models.TextField(
                        default="Thank you for your submission!", help_text="Message shown after successful submission"
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, help_text="Optional URL to redirect to after submission")),
                (
                    "save_to_leads",
                    models.BooleanField(default=False, help_text="Save form submissions to leads database"),
                ),
                (
                    "send_email_notification",
                    models.BooleanField(default=False, help_text="Send email notification on submission"),
                ),
                (
                    "notification_email",
                    models.EmailField(blank=True, help_text="Email address for notifications", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="Field label shown to user", max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("email", "Email Input"),
                            ("phone", "Phone Input"),
                            ("textarea", "Text Area"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio Buttons"),
                            ("file", "File Upload"),
                            ("date", "Date Picker"),
                            ("number", "Number Input"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(help_text="Internal field name (used in backend)", max_length=100)),
                ("placeholder", models.CharField(blank=True, help_text="Placeholder text", max_length=255)),
                ("help_text", models.CharField(blank=True, help_text="Help text shown below field", max_length=500)),
                (
                    "options",
                    models.JSONField(blank=True, default=list, help_text="Options for dropdown/radio/checkbox fields"),
                ),
                ("required", models.BooleanField(default=False, help_text="Is this field required?")),
                (
                    "min_length",
                    models.IntegerField(blank=True, help_text="Minimum length (for text fields)", null=True),
                ),
                (
                    "max_length",
                    models.IntegerField(blank=True, help_text="Maximum length (for text fields)", null=True),
                ),
                ("pattern", models.CharField(blank=True, help_text="Regex pattern for validation", max_length=255)),
                (
                    "allowed_file_types",
                    models.CharField(
                        blank=True, help_text="Comma-separated file extensions (e.g., pdf,doc,docx)", max_length=255
                    ),
                ),
                ("max_file_size", models.IntegerField(blank=True, help_text="Maximum file size in MB", null=True)),
                ("order", models.IntegerField(default=0, help_text="Display order (lower numbers first)")),
                ("width", models.CharField(default="full", help_text="Field width: full, half, third", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="forms.form"
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(help_text="Submitted form data")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "lead_created",
                    models.BooleanField(default=False, help_text="Was a lead created from this submission?"),
                ),
                ("lead_id", models.IntegerField(blank=True, help_text="ID of created lead", null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="forms.form"
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
