# Generated by Django 4.2.27 on 2026-01-18 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('stopped', 'Gestoppt'), ('failed', 'Fehlgeschlagen'), ('error', 'Fehler')], default='running', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='Prozess-ID')),
                ('params_snapshot', models.JSONField(default=dict, verbose_name='Parameter-Snapshot')),
                ('leads_found', models.IntegerField(default=0, verbose_name='Leads gefunden')),
                ('api_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='API-Kosten (USD)')),
                ('logs', models.TextField(blank=True, default='', verbose_name='Logs')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_control_runs', to=settings.AUTH_USER_MODEL, verbose_name='Gestartet von')),
            ],
            options={
                'verbose_name': 'Scraper-Lauf',
                'verbose_name_plural': 'Scraper-Läufe',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('all', 'Alle'), ('recruiter', 'Recruiter'), ('candidates', 'Kandidaten'), ('talent_hunt', 'Talent Hunt')], default='recruiter', max_length=50, verbose_name='Branche/Industry')),
                ('mode', models.CharField(choices=[('standard', 'Standard'), ('learning', 'Learning'), ('aggressive', 'Aggressive'), ('snippet_only', 'Snippet Only')], default='standard', max_length=50, verbose_name='Modus')),
                ('qpi', models.IntegerField(default=15, help_text='Anzahl der Queries pro Branche', verbose_name='QPI (Queries per Industry)')),
                ('daterestrict', models.CharField(blank=True, default='', help_text='Google CSE dateRestrict, z.B. d30, w8, m3', max_length=20, verbose_name='Date Restrict')),
                ('smart', models.BooleanField(default=True, help_text='AI-generierte Dorks aktivieren', verbose_name='Smart Mode')),
                ('force', models.BooleanField(default=False, help_text='Historie ignorieren (queries_done)', verbose_name='Force')),
                ('once', models.BooleanField(default=True, help_text='Einmaliger Lauf', verbose_name='Once')),
                ('dry_run', models.BooleanField(default=False, help_text='Test-Modus ohne tatsächliche Ausführung', verbose_name='Dry Run')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_control_configs', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Scraper-Konfiguration',
                'verbose_name_plural': 'Scraper-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='scraper_control.scraperrun', verbose_name='Scraper-Lauf')),
            ],
            options={
                'verbose_name': 'Scraper-Log',
                'verbose_name_plural': 'Scraper-Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['run', 'created_at'], name='scraper_con_run_id_628543_idx')],
            },
        ),
    ]
