# Generated by Django 6.0.1 on 2026-01-19 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Interner Name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Anzeigename')),
                ('base_url', models.URLField(verbose_name='Basis-URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('rate_limit_seconds', models.FloatField(default=3.0, help_text='Pause zwischen Requests', verbose_name='Rate Limit (Sek)')),
                ('max_results', models.IntegerField(default=20, verbose_name='Max. Ergebnisse')),
                ('requires_login', models.BooleanField(default=False, verbose_name='Login erforderlich')),
                ('difficulty', models.CharField(choices=[('low', 'Einfach'), ('medium', 'Mittel'), ('high', 'Schwer'), ('very_high', 'Sehr schwer')], default='medium', max_length=20, verbose_name='Schwierigkeit')),
                ('urls', models.JSONField(blank=True, default=list, help_text='Liste der zu crawlenden URLs', verbose_name='URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal-Quelle',
                'verbose_name_plural': 'Portal-Quellen',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SearchDork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Google Dork Query', verbose_name='Such-Query')),
                ('category', models.CharField(choices=[('default', 'Standard'), ('candidates', 'Kandidaten'), ('recruiter', 'Recruiter'), ('talent_hunt', 'Talent Hunt'), ('social', 'Social Media'), ('portal', 'Portal-spezifisch'), ('custom', 'Benutzerdefiniert')], default='default', max_length=50, verbose_name='Kategorie')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.IntegerField(default=0, verbose_name='Priorität')),
                ('times_used', models.IntegerField(default=0, verbose_name='Verwendungen')),
                ('leads_found', models.IntegerField(default=0, verbose_name='Leads gefunden')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Erfolgsrate')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt verwendet')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='KI-generiert')),
                ('ai_prompt', models.TextField(blank=True, verbose_name='KI-Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Such-Dork',
                'verbose_name_plural': 'Such-Dorks',
                'ordering': ['-priority', '-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='SearchRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Stadt/Region')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_metropolis', models.BooleanField(default=False, help_text='Große Stadt mit mehr Queries', verbose_name='Metropole')),
                ('priority', models.IntegerField(default=0, help_text='Höher = wird zuerst gescraped', verbose_name='Priorität')),
            ],
            options={
                'verbose_name': 'Such-Region',
                'verbose_name_plural': 'Such-Regionen',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='allow_pdf',
            field=models.BooleanField(default=False, verbose_name='PDF-Dateien erlauben'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='async_limit',
            field=models.IntegerField(default=35, help_text='Max. parallele Requests', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Async Limit'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='circuit_breaker_penalty',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Circuit Breaker Penalty (Sek)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='confidence_threshold',
            field=models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Confidence Threshold'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='default_quality_score',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Quality Score'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_bing',
            field=models.BooleanField(default=False, verbose_name='Bing Search aktivieren'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_kleinanzeigen',
            field=models.BooleanField(default=True, verbose_name='Kleinanzeigen aktivieren'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_perplexity',
            field=models.BooleanField(default=False, verbose_name='Perplexity AI aktivieren'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='enable_telefonbuch',
            field=models.BooleanField(default=True, verbose_name='Telefonbuch-Enrichment'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='http2_enabled',
            field=models.BooleanField(default=True, verbose_name='HTTP/2 aktivieren'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='http_timeout',
            field=models.IntegerField(default=10, help_text='Request Timeout in Sekunden', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='HTTP Timeout (Sek)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_concurrent_portals',
            field=models.IntegerField(default=5, verbose_name='Max. parallele Portale'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_content_length',
            field=models.IntegerField(default=2097152, help_text='Standard: 2MB', verbose_name='Max. Content-Größe (Bytes)'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_google_pages',
            field=models.IntegerField(default=2, help_text='Seiten pro Query', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Max. Google-Seiten'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='max_per_domain',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Max. Leads pro Domain'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='min_score',
            field=models.IntegerField(default=40, help_text='Leads unter diesem Score werden verworfen', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mindest-Score'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='parallel_portal_crawl',
            field=models.BooleanField(default=True, verbose_name='Paralleles Portal-Crawling'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='pool_size',
            field=models.IntegerField(default=12, help_text='Connection Pool Größe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Pool Size'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='retry_max_per_url',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Max. Retries pro URL'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='sleep_between_queries',
            field=models.FloatField(default=2.7, help_text='Pause zwischen Google-Queries', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(30)], verbose_name='Query-Pause (Sek)'),
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('domain', 'Domain'), ('path_pattern', 'Pfad-Muster'), ('mailbox_prefix', 'Email-Prefix')], max_length=20, verbose_name='Typ')),
                ('value', models.CharField(max_length=255, verbose_name='Wert')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Grund')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklist-Eintrag',
                'verbose_name_plural': 'Blacklist-Einträge',
                'ordering': ['entry_type', 'value'],
                'unique_together': {('entry_type', 'value')},
            },
        ),
    ]
