# Generated by Django 6.0.1 on 2026-01-19 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0003_seed_scraper_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='max_concurrent_portals',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Max. parallele Portale'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='max_content_length',
            field=models.IntegerField(default=2097152, help_text='Standard: 2MB, Max: 100MB', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(104857600)], verbose_name='Max. Content-Größe (Bytes)'),
        ),
    ]
