# Generated by Django 4.2.27 on 2026-01-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0004_alter_scraperconfig_max_concurrent_portals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='industry',
            field=models.CharField(choices=[('all', 'Alle'), ('recruiter', 'Recruiter'), ('candidates', 'Kandidaten'), ('talent_hunt', 'Talent Hunt'), ('handelsvertreter', 'Handelsvertreter'), ('nrw', 'NRW Regional'), ('social', 'Social Media'), ('solar', 'Solar/Energie'), ('telekom', 'Telekommunikation'), ('versicherung', 'Versicherung'), ('bau', 'Baubranche'), ('ecom', 'E-Commerce'), ('household', 'Haushalt'), ('d2d', 'Door-to-Door'), ('callcenter', 'Call Center')], default='recruiter', max_length=50, verbose_name='Branche/Industry'),
        ),
    ]
