# Generated by Django 6.0.1 on 2026-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0005_alter_scraperconfig_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='allow_insecure_ssl',
            field=models.BooleanField(default=False, help_text='⚠️ WARNUNG: Deaktiviert SSL-Zertifikat-Validierung. Nur für Entwicklung/Testing!', verbose_name='Unsichere SSL-Verbindungen erlauben'),
        ),
    ]
