# Generated by Django 4.2.27 on 2026-01-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0007_init_config_from_env'),
        ('scraper_control', '0007_observability_enhancements'),
    ]

    operations = [
    ]
