# Generated by Django 5.2 on 2026-01-19
# Migration for extended AI integration fields on SearchDork

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0007_observability_enhancements'),
    ]

    operations = [
        # Add new fields for AI learning integration
        migrations.AddField(
            model_name='searchdork',
            name='leads_with_phone',
            field=models.IntegerField(
                default=0, 
                verbose_name='Leads mit Telefon',
                help_text='Anzahl der Leads mit erfolgreicher Telefonnummer-Extraktion'
            ),
        ),
        migrations.AddField(
            model_name='searchdork',
            name='total_search_results',
            field=models.IntegerField(
                default=0, 
                verbose_name='Gesamte Suchergebnisse',
                help_text='Kumulierte Anzahl der Google-Suchergebnisse'
            ),
        ),
        migrations.AddField(
            model_name='searchdork',
            name='extraction_patterns',
            field=models.JSONField(
                default=list, 
                blank=True, 
                verbose_name='Extraktionsmuster',
                help_text='Erfolgreiche CSS/XPath-Muster die mit diesem Dork funktionieren'
            ),
        ),
        migrations.AddField(
            model_name='searchdork',
            name='top_domains',
            field=models.JSONField(
                default=list, 
                blank=True, 
                verbose_name='Top-Domains',
                help_text='Domains mit höchster Erfolgsrate für diesen Dork'
            ),
        ),
        migrations.AddField(
            model_name='searchdork',
            name='phone_patterns',
            field=models.JSONField(
                default=list, 
                blank=True, 
                verbose_name='Telefon-Muster',
                help_text='Erfolgreiche Telefonnummer-Patterns'
            ),
        ),
        migrations.AddField(
            model_name='searchdork',
            name='last_synced_at',
            field=models.DateTimeField(
                null=True, 
                blank=True, 
                verbose_name='Letzte Synchronisierung',
                help_text='Zeitpunkt der letzten Sync mit SQLite Learning-DB'
            ),
        ),
    ]
