# Generated by Django on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0008_expand_portal_urls'),
        ('scraper_control', '0008_merge_20260119_2045'),
        ('scraper_control', '0008_searchdork_ai_learning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='config_version',
            field=models.IntegerField(
                default=1,
                editable=False,
                verbose_name='Konfigurationsversion',
                help_text='Steigt bei jeder Speicherung, damit laufende Scraper Änderungen erkennen'
            ),
        ),
    ]
