# Generated by Django 4.2.27 on 2026-01-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0007_add_process_retry_circuit_breaker_fields'),
        ('scraper_control', '0009_add_config_version'),
    ]

    operations = [
    ]
