# Generated by Django 4.2.27 on 2026-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0010_merge_20260119_2338'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='scraper_con_run_id_a23e91_idx',
            old_name='scraper_con_run_id_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='scraper_con_severit_d2cf44_idx',
            old_name='scraper_con_severity_2b3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='scraper_con_portal_4a0000_idx',
            old_name='scraper_con_portal_3c4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='scraper_con_error_t_aaf891_idx',
            old_name='scraper_con_error_t_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='scraperlog',
            new_name='scraper_con_level_f58b59_idx',
            old_name='scraper_con_level_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='scraperlog',
            new_name='scraper_con_portal_8c82b5_idx',
            old_name='scraper_con_portal_0d1e2f_idx',
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='bing_api_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Bing API Key'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='gcs_cxs',
            field=models.CharField(blank=True, default='', help_text='Comma-separierte Custom Search Identifiers', max_length=512, verbose_name='Google CSE CXs'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='gcs_keys',
            field=models.CharField(blank=True, default='', help_text='Komma-separierte Google CSE Keys', max_length=512, verbose_name='Google CSE API Keys'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='google_cse_api_key',
            field=models.CharField(blank=True, default='', help_text='Einzelkey für Google Custom Search', max_length=512, verbose_name='Google CSE API Key'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='Override für die OpenAI API (z.B. sk-...)', max_length=512, verbose_name='OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='perplexity_api_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Perplexity API Key'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('learning', 'Selbstlernend'), ('aggressive', 'Aggressiv'), ('snippet_only', 'Nur Snippets')], default='standard', max_length=50, verbose_name='Modus'),
        ),
    ]
