# Generated by Django 4.2.27 on 2026-01-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_control', '0011_rename_scraper_con_run_id_1a2b3c_idx_scraper_con_run_id_a23e91_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstmals gesehen am')),
                ('first_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls_seen', to='scraper_control.scraperrun', verbose_name='Erster Scraper-Lauf')),
            ],
            options={
                'verbose_name': 'Gesehene URL',
                'verbose_name_plural': 'Gesehene URLs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='scraper_con_url_9dd91b_idx'), models.Index(fields=['created_at'], name='scraper_con_created_33ec7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(unique=True, verbose_name='Such-Query')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstmals ausgeführt am')),
                ('last_executed_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt ausgeführt am')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries_done', to='scraper_control.scraperrun', verbose_name='Letzter Scraper-Lauf')),
            ],
            options={
                'verbose_name': 'Ausgeführte Query',
                'verbose_name_plural': 'Ausgeführte Queries',
                'ordering': ['-last_executed_at'],
                'indexes': [models.Index(fields=['query'], name='scraper_con_query_15943c_idx'), models.Index(fields=['last_executed_at'], name='scraper_con_last_ex_f5ccce_idx')],
            },
        ),
    ]
