# Generated by Django 4.2.27 on 2026-01-17 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('NEW', 'Neu'), ('CONTACTED', 'Kontaktiert'), ('VOICEMAIL', 'Voicemail'), ('INTERESTED', 'Interessiert'), ('INTERVIEW', 'Interview'), ('HIRED', 'Eingestellt'), ('NOT_INTERESTED', 'Kein Interesse'), ('INVALID', 'Ungültig')], default='NEW', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('scraper', 'Scraper'), ('landing_page', 'Landing Page'), ('manual', 'Manuell'), ('referral', 'Empfehlung')], default='scraper', max_length=20, verbose_name='Quelle')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Quell-URL')),
                ('source_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quell-Detail')),
                ('quality_score', models.IntegerField(default=50, verbose_name='Qualitäts-Score')),
                ('lead_type', models.CharField(choices=[('active_salesperson', 'Aktiver Vertriebler'), ('team_member', 'Team-Mitglied'), ('freelancer', 'Freelancer'), ('hr_contact', 'HR-Kontakt'), ('candidate', 'Jobsuchender'), ('unknown', 'Unbekannt')], default='unknown', max_length=30, verbose_name='Lead-Typ')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position/Rolle')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='Jahre Erfahrung')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Standort')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('xing_url', models.URLField(blank=True, null=True, verbose_name='XING URL')),
                ('interest_level', models.IntegerField(default=0, help_text='1-5 Skala, 0 = nicht bewertet', verbose_name='Interesse-Level')),
                ('call_count', models.IntegerField(default=0, verbose_name='Anzahl Anrufe')),
                ('last_called_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Anruf')),
                ('next_followup_at', models.DateTimeField(blank=True, null=True, verbose_name='Nächstes Follow-Up')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('email_sent_count', models.IntegerField(default=0, verbose_name='Emails gesendet')),
                ('email_opens', models.IntegerField(default=0, verbose_name='Email Öffnungen')),
                ('email_clicks', models.IntegerField(default=0, verbose_name='Email Klicks')),
                ('last_email_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-quality_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('WELCOME', 'Willkommen'), ('FOLLOWUP_1', 'Follow-Up 1'), ('FOLLOWUP_2', 'Follow-Up 2'), ('FOLLOWUP_3', 'Follow-Up 3'), ('INTERVIEW_INVITE', 'Interview-Einladung'), ('CUSTOM', 'Individuell')], max_length=20, verbose_name='Email-Typ')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('brevo_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Geöffnet am')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Geklickt am')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Email-Log',
                'verbose_name_plural': 'Email-Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('CONNECTED', 'Verbunden'), ('VOICEMAIL', 'Voicemail'), ('BUSY', 'Besetzt'), ('NO_ANSWER', 'Keine Antwort'), ('WRONG_NUMBER', 'Falsche Nummer'), ('CALLBACK_REQUESTED', 'Rückruf gewünscht')], max_length=20, verbose_name='Ergebnis')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Dauer (Sekunden)')),
                ('interest_level', models.IntegerField(default=0, help_text='1-5 Skala', verbose_name='Interesse-Level')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('called_at', models.DateTimeField(auto_now_add=True, verbose_name='Angerufen am')),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Angerufen von')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Anruf-Log',
                'verbose_name_plural': 'Anruf-Logs',
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_lead_source_200868_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['quality_score'], name='leads_lead_quality_7bbbef_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type'], name='leads_lead_lead_ty_f6ba1c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
