# Generated by Django 4.2.27 on 2026-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='outcome',
            field=models.CharField(choices=[('CONNECTED', 'Erreicht'), ('VOICEMAIL', 'Voicemail'), ('NO_ANSWER', 'Keine Antwort'), ('BUSY', 'Besetzt'), ('WRONG_NUMBER', 'Falsche Nummer'), ('CALLBACK', 'Rückruf vereinbart'), ('INTERESTED', 'Interessiert'), ('NOT_INTERESTED', 'Kein Interesse')], max_length=20, verbose_name='Ergebnis'),
        ),
    ]
