# Generated by Django 4.2.27 on 2026-01-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_calllog_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="z.B. 'scraper_db'", max_length=50, unique=True, verbose_name='Quelle')),
                ('last_sync_at', models.DateTimeField(help_text='Zeitpunkt des letzten erfolgreichen Syncs', verbose_name='Letzter Sync')),
                ('last_lead_id', models.IntegerField(default=0, help_text='ID des letzten importierten Leads aus der Quelle', verbose_name='Letzte Lead-ID')),
                ('leads_imported', models.IntegerField(default=0, help_text='Anzahl der insgesamt importierten Leads', verbose_name='Leads importiert')),
                ('leads_updated', models.IntegerField(default=0, help_text='Anzahl der aktualisierten Leads', verbose_name='Leads aktualisiert')),
                ('leads_skipped', models.IntegerField(default=0, help_text='Anzahl der übersprungenen Leads', verbose_name='Leads übersprungen')),
            ],
            options={
                'verbose_name': 'Sync-Status',
                'verbose_name_plural': 'Sync-Status',
                'ordering': ['-last_sync_at'],
            },
        ),
    ]
