# Generated by Django 4.2.27 on 2026-01-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_add_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('status', models.CharField(choices=[('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('stopped', 'Gestoppt')], default='running', max_length=20, verbose_name='Status')),
                ('leads_found', models.IntegerField(default=0, verbose_name='Leads gefunden')),
                ('leads_saved', models.IntegerField(default=0, verbose_name='Leads gespeichert')),
                ('leads_rejected', models.IntegerField(default=0, verbose_name='Leads abgelehnt')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='Konfiguration')),
                ('logs', models.TextField(blank=True, default='', verbose_name='Logs')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='Prozess-ID')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gestartet von')),
            ],
            options={
                'verbose_name': 'Scraper-Lauf',
                'verbose_name_plural': 'Scraper-Läufe',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=40, help_text='Minimaler Qualitäts-Score für Leads (0-100)', verbose_name='Minimaler Score')),
                ('max_results_per_domain', models.IntegerField(default=3, help_text='Maximale Anzahl von Ergebnissen pro Domain', verbose_name='Max. Ergebnisse pro Domain')),
                ('request_timeout', models.IntegerField(default=12, help_text='Timeout für HTTP-Requests in Sekunden', verbose_name='Request Timeout (Sekunden)')),
                ('pool_size', models.IntegerField(default=10, help_text='Anzahl paralleler Worker', verbose_name='Pool-Größe')),
                ('internal_depth_per_domain', models.IntegerField(default=2, help_text='Wie tief interne Links verfolgt werden sollen', verbose_name='Interne Tiefe pro Domain')),
                ('allow_pdf', models.BooleanField(default=True, help_text='PDF-Dateien crawlen', verbose_name='PDFs erlauben')),
                ('allow_insecure_ssl', models.BooleanField(default=False, help_text='Selbstsignierte SSL-Zertifikate akzeptieren', verbose_name='Unsichere SSL-Verbindungen erlauben')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Scraper-Konfiguration',
                'verbose_name_plural': 'Scraper-Konfigurationen',
            },
        ),
    ]
