# Generated by Django 4.2.27 on 2026-01-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_create_default_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperrun',
            name='started_by',
        ),
        migrations.DeleteModel(
            name='ScraperConfig',
        ),
        migrations.DeleteModel(
            name='ScraperRun',
        ),
    ]
