# Generated by Django 4.2.27 on 2026-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_scraperrun_started_by_delete_scraperconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AI-Kategorie'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI-Zusammenfassung'),
        ),
        migrations.AddField(
            model_name='lead',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verfügbarkeit'),
        ),
        migrations.AddField(
            model_name='lead',
            name='candidate_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kandidaten-Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='commission_hint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provisionshinweis'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firmengröße'),
        ),
        migrations.AddField(
            model_name='lead',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='AI-Konfidenz-Score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_preference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontaktpräferenz'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cv_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lebenslauf-URL'),
        ),
        migrations.AddField(
            model_name='lead',
            name='data_quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Datenqualität'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hiring_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Einstellungsvolumen'),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branche'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Letzte Aktualisierung (Scraper)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobilität/Reisebereitschaft'),
        ),
        migrations.AddField(
            model_name='lead',
            name='opening_line',
            field=models.TextField(blank=True, null=True, verbose_name='Eröffnungszeile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon-Typ'),
        ),
        migrations.AddField(
            model_name='lead',
            name='private_address',
            field=models.TextField(blank=True, null=True, verbose_name='Privatadresse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil-URL'),
        ),
        migrations.AddField(
            model_name='lead',
            name='recency_indicator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aktualitäts-Indikator'),
        ),
        migrations.AddField(
            model_name='lead',
            name='salary_hint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gehaltshinweis'),
        ),
        migrations.AddField(
            model_name='lead',
            name='skills',
            field=models.JSONField(blank=True, help_text='Array von Fähigkeiten', null=True, verbose_name='Fähigkeiten'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.JSONField(blank=True, help_text='Array von Tags', null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp-Link'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('active_salesperson', 'Aktiver Vertriebler'), ('team_member', 'Team-Mitglied'), ('freelancer', 'Freelancer'), ('hr_contact', 'HR-Kontakt'), ('candidate', 'Jobsuchender'), ('talent_hunt', 'Talent Hunt'), ('recruiter', 'Recruiter'), ('job_ad', 'Stellenanzeige'), ('company', 'Firmenkontakt'), ('individual', 'Einzelperson'), ('unknown', 'Unbekannt')], default='unknown', max_length=30, verbose_name='Lead-Typ'),
        ),
    ]
