# Generated by Django 4.2.27 on 2026-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_add_email_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Nur Ziffern für schnellen Abgleich', max_length=50, null=True, verbose_name='Normalisierte Telefonnummer'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email_normalized'], name='leads_lead_email_n_ddaf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['normalized_phone'], name='leads_lead_normali_b242fd_idx'),
        ),
    ]
