# Generated by Django 4.2 on 2024-01-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_normalized_phone_and_more'),
    ]

    operations = [
        # Add composite indexes for common query patterns
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'status'], name='idx_lead_type_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'quality_score'], name='idx_status_quality'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='idx_source_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_assigned_status'),
        ),
        
        # Indexes for sorting and filtering
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-quality_score', '-created_at'], name='idx_quality_created_desc'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['updated_at'], name='idx_updated_at'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_called_at'], name='idx_last_called'),
        ),
        
        # Indexes for data quality and scoring
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['confidence_score'], name='idx_confidence'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['data_quality'], name='idx_data_quality'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['interest_level'], name='idx_interest_level'),
        ),
        
        # Add data integrity constraints
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(quality_score__gte=0) & models.Q(quality_score__lte=100),
                name='quality_score_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(confidence_score__isnull=True) | 
                      (models.Q(confidence_score__gte=0) & models.Q(confidence_score__lte=100)),
                name='confidence_score_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(data_quality__isnull=True) | 
                      (models.Q(data_quality__gte=0) & models.Q(data_quality__lte=100)),
                name='data_quality_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(interest_level__gte=0) & models.Q(interest_level__lte=5),
                name='interest_level_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(experience_years__isnull=True) | models.Q(experience_years__gte=0),
                name='experience_years_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(hiring_volume__isnull=True) | models.Q(hiring_volume__gte=0),
                name='hiring_volume_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(call_count__gte=0),
                name='call_count_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(email_sent_count__gte=0),
                name='email_sent_count_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(email_opens__gte=0),
                name='email_opens_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(
                check=models.Q(email_clicks__gte=0),
                name='email_clicks_positive',
            ),
        ),
    ]
